/**
 * Regenerate parity-vectors.json from the JS implementation, which is
 * canonical. Run after any intentional behaviour change, then re-run the
 * Swift parity test to confirm the twin still agrees.
 *
 *   node generate-vectors.mjs > parity-vectors.json
 */
import {
  getORPIndex, getActualORPIndex, splitWordForDisplay,
  getWordDelay, formatTimeRemaining, isRenderable,
  findNearestRenderableWordIndex,
} from './rsvpTiming.js';

const WORDS = [
  // length buckets, including the 18+ tier that the Swift twin was missing
  'a', 'to', 'the', 'word', 'hello', 'reading', 'beautiful', 'interesting',
  'presentation', 'uncharacteristic', 'counterintelligence',
  'internationalization', 'electroencephalography',
  'antidisestablishmentarianism',
  // punctuation and clause endings
  'home.', 'wait!', 'why?', 'thus;', 'note:', 'however,', 'of,', 'It.', 'Go!',
  // em/en-dash pause markers vs non-pausing compound hyphen
  'home—', 'range–', 'well-known',
  // footnote markers and closing quotes/brackets hiding the punctuation
  'theology.2', 'Platonism,1', 'hierarchies.¹', 'said."', "end.'", '(note.)',
  // break markers
  '⟩The', '⟩of,', '⟩home.', '\n',
  // unicode: accents, non-Latin scripts, numerics
  'café', 'naïve', 'résumé', 'Ω', '日本語の文章', 'Привет', '2026', '12,345',
  // degenerate
  '', "don't", 'e-mail',
];

const WPMS = [200, 400, 1000];
const PARAMS = [
  { pauseOnPunctuation: true, punct: 2, lengthMult: 0, lineBreak: 3 },
  { pauseOnPunctuation: true, punct: 2.5, lengthMult: 5, lineBreak: 3 },
  { pauseOnPunctuation: false, punct: 2, lengthMult: 0, lineBreak: 3 },
];

const orp = WORDS.map((word) => {
  const parts = splitWordForDisplay(word);
  return {
    word,
    orpIndex: getORPIndex(word),
    actualOrpIndex: getActualORPIndex(word),
    before: parts.before, orp: parts.orp, after: parts.after,
    renderable: isRenderable(word),
  };
});

const delays = [];
for (const word of WORDS) {
  for (const wpm of WPMS) {
    for (const p of PARAMS) {
      delays.push({
        word, wpm,
        pauseOnPunctuation: p.pauseOnPunctuation,
        punctuationMultiplier: p.punct,
        wordLengthMultiplier: p.lengthMult,
        lineBreakMultiplier: p.lineBreak,
        // rounded to 6dp: JS and Swift both use IEEE-754 doubles, but the
        // decimal round-trip through JSON is where they can drift
        delayMs: Number(getWordDelay(word, wpm, p.pauseOnPunctuation, p.punct, p.lengthMult, p.lineBreak).toFixed(6)),
      });
    }
  }
}

const timeRemaining = [
  [0, 300], [1, 300], [150, 300], [300, 300], [301, 300], [7, 400], [99999, 250],
  [100, 0], [-5, 300],
].map(([remainingWords, wpm]) => ({
  remainingWords, wpm, formatted: formatTimeRemaining(remainingWords, wpm),
}));

const NEAREST_TOKENS = ['\n', '', '  ', 'first', 'second', '\n', 'third', '\n'];
const nearestRenderable = [-1, 0, 1, 2, 3, 5, 7, 99].map((startIndex) => ({
  startIndex,
  index: findNearestRenderableWordIndex(NEAREST_TOKENS, startIndex),
}));

console.log(JSON.stringify({
  _comment: 'Generated by generate-vectors.mjs from rsvpTiming.js (canonical). Do not hand-edit.',
  orp, delays, timeRemaining,
  nearestRenderable: { tokens: NEAREST_TOKENS, cases: nearestRenderable },
}, null, 2));
